version: '3.8'
services:
  app:
    build: .
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
      - DEFAULT_USER_PASSWORD=${DEFAULT_USER_PASSWORD}
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    depends_on:
      - db
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "mongo:27017"]
      interval: 30s
      timeout: 10s
      retries: 5
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "27017:27017"
