version: '3.8'
services:
  app:
    build: .
    environment:
      MONGO_URL: "mongodb://db:27017/movies"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules  
    depends_on:
      - db
    ports:
      - "3000:3000"
  db:
    image: mongo
    container_name: 'movie-db'
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017

